apiVersion: v1
kind: Service
metadata:
  name: django-test-service
spec:
  selector:
    app: python-crud
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-crud
spec:
  selector:
    matchLabels:
      app: python-crud
  replicas: 3
  template:
    metadata:
      labels:
        app: python-crud
    spec:
      containers:
        - name: python-crud
          image: mariannesalomao/django-kubernetes
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000